//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Amidelaposte
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Commandes = new HashSet<Commande>();
        }
    
        public string PrenomClient { get; set; }
        public string NomClient { get; set; }
        public int IdClient { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Adresse { get; set; }
        public string CodePostal { get; set; }
        public int IdVille { get; set; }
        public string Telephone { get; set; }
        public bool EstMajeur { get; set; }
        public bool EstAdmin { get; set; }
    
        public virtual Ville Ville { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commande> Commandes { get; set; }
    }
}
