//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROJET_FINAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commande()
        {
            this.Objets = new HashSet<Objet>();
<<<<<<< HEAD
            
=======
           
>>>>>>> e1a4b638005278e3b5c8744d75a4adb3839dbe76
        }
    
        public int IdCommande { get; set; }
        public int IdClient { get; set; }
        public Nullable<int> idLivreur { get; set; }
        public string InfosSup { get; set; }
        public bool EstMajeur { get; set; }
        public string Adresse { get; set; }
        public Nullable<int> IdVille { get; set; }
        public string CodePostal { get; set; }
        public Nullable<System.DateTime> DateComm { get; set; }
<<<<<<< HEAD
=======
        
>>>>>>> e1a4b638005278e3b5c8744d75a4adb3839dbe76
        public virtual Client Client { get; set; }
        public virtual Livreur Livreur { get; set; }
        public virtual Ville Ville { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Objet> Objets { get; set; }
    }
}
